extends: standard

env:
  jest: true

parser: babel-eslint
parserOptions:
  ecmaVersion: 6

rules:
  quotes: ["error", "double", {avoidEscape: true}]
  space-before-function-paren: ["error", "never"]
  semi: ["error", "always"]
